on: [push]

jobs:
  accelq_ci_job:
    runs-on: ubuntu-latest
    name: Execute ACCELQ CI JOB
    steps:
    - name: Automation Step
      id: accelq_auto
      uses: accelq/accelq-ci-github-actions@v0.3
      with:
        appURL: 'https://poc.accelq.io/'
        userName: 'tenantAdmin@democopy.com'
        apiKey: '8dshi7d2h1aZ7QPTO8JCr825YV4XJLm9'
        tenantCode: 'democopy'
        jobId: '92'